import os
import json
import sys
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

def write_output(response_text: str, format_type: str = "markdown"):
    """Write output JSON adhering to the aiKart container contract (/aikart/output.json)."""
    target_path = Path("/aikart/output.json")
    try:
        target_path.parent.mkdir(parents=True, exist_ok=True)
        with open(target_path, "w", encoding="utf-8") as f:
            json.dump({"format": format_type, "response": response_text}, f, indent=2)
        print(f"[aiKart Runner] Successfully wrote output to {target_path}")
        return
    except Exception as e:
        print(f"[aiKart Runner] Primary path /aikart/output.json failed ({e}), writing fallback local output.json")
    
    fallback_path = Path("output.json")
    with open(fallback_path, "w", encoding="utf-8") as f:
        json.dump({"format": format_type, "response": response_text}, f, indent=2)
    print(f"[aiKart Runner] Successfully wrote fallback output to {fallback_path.resolve()}")

def main():
    raw_input = os.environ.get("AIKART_INPUT", "")
    print(f"[aiKart Runner] Initialized. AIKART_INPUT: {raw_input[:200] if raw_input else '(Empty/Default)'}")

    prompt = ""
    mode = "inbox-process"
    model_choice = "gemini-2.0-flash"

    if raw_input:
        try:
            parsed = json.loads(raw_input)
            if isinstance(parsed, dict):
                prompt = parsed.get("prompt") or parsed.get("topic") or parsed.get("email_body") or ""
                mode = parsed.get("mode", mode)
                model_choice = parsed.get("model", model_choice)
            elif isinstance(parsed, str):
                prompt = parsed
        except Exception:
            prompt = raw_input

    if not prompt:
        prompt = "Hi team, I would like to inquire about your AI automation services, plans, and custom development options."

    try:
        from src.agents import Agents
        agents = Agents()
        
        # 1. Categorize query
        print("[aiKart Runner] Categorizing email input...")
        cat_result = agents.categorize_email.invoke({"email": prompt})
        category = getattr(cat_result, "category", None)
        category_str = category.value if hasattr(category, "value") else str(category or "product_enquiry")

        # 2. Retrieve context from RAG knowledge base if applicable
        rag_info = ""
        if category_str == "product_enquiry" or mode == "rag-query":
            print("[aiKart Runner] Retrieving RAG knowledge context...")
            retrieved_docs = agents.retriever.invoke(prompt)
            if retrieved_docs:
                rag_info = "\n---\n".join([doc.page_content for doc in retrieved_docs])

        # 3. Draft reply
        print("[aiKart Runner] Generating draft reply with LLM...")
        writer_input = (
            f"# **EMAIL CATEGORY:** {category_str}\n\n"
            f"# **EMAIL CONTENT:**\n{prompt}\n\n"
            f"# **INFORMATION:**\n{rag_info}"
        )
        draft_result = agents.email_writer.invoke({"history": [], "email_information": writer_input})
        draft_email = getattr(draft_result, "email", None) or str(draft_result)

        # 4. Format markdown response
        formatted_response = (
            f"### 📥 Customer Support Query\n"
            f"> {prompt}\n\n"
            f"### 🏷️ Categorization Analysis\n"
            f"- **Detected Category:** `{category_str}`\n"
            f"- **Target Model:** `{model_choice}`\n\n"
        )
        if rag_info:
            formatted_response += f"### 📚 Knowledge Base Context (RAG)\n{rag_info}\n\n"

        formatted_response += (
            f"### ✉️ Automated Draft Response\n"
            f"```text\n{draft_email}\n```\n\n"
            f"---\n"
            f"*Generated by LangGraph Email Automation Agent on aiKart Platform.*"
        )

        write_output(formatted_response, "markdown")
        sys.exit(0)

    except Exception as e:
        import traceback
        err_trace = traceback.format_exc()
        print(f"[aiKart Runner Error] {e}\n{err_trace}", file=sys.stderr)
        err_msg = (
            f"### ❌ Execution Error\n"
            f"An error occurred while executing the email agent workflow:\n"
            f"```\n{str(e)}\n\n{err_trace[:500]}\n```"
        )
        write_output(err_msg, "markdown")
        sys.exit(1)

if __name__ == "__main__":
    main()
